# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1530168676cb49b45be81ff7be4abbf7f03bb89070bb0ed393b869b18b75abd1864ddef6dff2ac9f67556da201de018f45612b7f0e500b485225f562e101e1f0

test:
  secret_key_base: 599880eeef3ebd26ea98c338ac981d839c4c2ce693f6263c09cecdf25abd0ec5888409fb6a2759afb52477e8c2ba719e64f2d23f5ece5504ca6aa88242540927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
